/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Posts {
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  details: Generated<string | null>;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  lastSignedInAt: Timestamp | null;
  password: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  posts: Posts;
  users: Users;
}
